version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: publicclassdev-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - my-network

networks:
  my-network:
    name: my-network
