version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: publicclassdev-mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d

networks:
  my-network:
    external: true