version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: publicclassdev-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: projectdev
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d

networks:
  my-network:
    external: true