POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "name" : "홍길동",
  "email" : "asdf1234@email.com",
  "password" : "Asdf1234!",
  "admin" : "true",
  "adminToken" : "admin1234!"
}

###
# curl -X POST --location "http://localhost:8080/api/users/signup"
#    -H "Content-Type: application/json"
#    -d '{
#          "email" : "asdf1234@email.com",
#          "password" : "Asdf1234!"
#        }'
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email" : "asdf1234@email.com",
  "password" : "Asdf1234!"
}

> {%
client.global.set("Authorization", response.headers.valueOf("Authorization"));
client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}
###

###
GET http://localhost:8080/api/users/profiles
Content-Type: application/json
Authorization: {{Authorization}}

###
PATCH http://localhost:8080/api/users/profiles
Content-Type: application/json
Authorization: {{Authorization}}

{
  "name" : "홍길동",
  "password": "Asdf1234!",
  "intro": "자기소개"
}



