###
# curl -X POST --location "http://localhost:8080/api/users/signup"
#    -H "Content-Type: application/json"
#    -d '{
#         "name" : "홍길동",
#         "email" : "asdf1234@email.com",
#         "password" : "Asdf1234!",
#         "admin" : "true",
#         "adminToken" : "admin1234!"
#       }'
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "name" : "김길동",
  "email" : "asdf2345@email.com",
  "password" : "Asdf2345!",
  "admin" : "false",
  "adminToken" : ""
}

###
# curl -X POST --location "http://localhost:8080/api/users/login"
#    -H "Content-Type: application/json"
#    -d '{
#          "email" : "asdf1234@email.com",
#          "password" : "Asdf1234!"
#        }'
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email" : "asdf1234@email.com",
  "password" : "Asdf1234!"
}

> {%
client.global.set("Authorization", response.headers.valueOf("Authorization"));
client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}
###

###
# curl -X GET --location "http://localhost:8080/api/users/profiles"
#    -H "Authorization: Bearer accesstoken"
#    -H "Content-Type: application/json"
GET http://localhost:8080/api/users/profiles
Authorization: {{Authorization}}
Content-Type: application/json

###
# curl -X PATCH --location "http://localhost:8080/api/users/profiles"
#    -H "Authorization: Bearer accesstoken"
#    -H "Content-Type: application/json"
#    -d '{
#          "name" : "홍길동",
#          "password": "Asdf1111!",
#          "intro": "자기소개"
#        }'
PATCH http://localhost:8080/api/users/profiles
Authorization: {{Authorization}}
Content-Type: application/json

{
  "name" : "홍길동",
  "password" : "Asdf1111!",
  "intro" : "자기소개"
}

###
# curl -X POST --location "http://localhost:8080/api/users/logout"
#    -H "Authorization: Bearer accesstoken"
#    -H "Content-Type: application/json"
POST http://localhost:8080/api/users/logout
Authorization: {{Authorization}}
Content-Type: application/json

> {%
  client.global.clear("Authorization")
  client.global.clear("RefreshToken")
%}

###
# curl -X POST --location "http://localhost:8080/api/users/withdraw"
#    -H "Authorization: Bearer accesstoken"
#    -H "Content-Type: application/json"
#    -d '{
#          "email" : "asdf1234@email.com",
#          "password" : "Asdf1111!"
#        }'
POST http://localhost:8080/api/users/withdraw
Authorization: {{Authorization}}
Content-Type: application/json

{
  "email": "asdf1234@email.com",
  "password": "Asdf1111!"
}
> {%
  client.global.clear("Authorization")
  client.global.clear("RefreshToken")
%}

###
# curl -X POST --location "http://localhost:8080/api/users/reissue-token"
#    -H "Content-Type: application/json"
#    -d '{
#          "refreshToken": "{{RefreshToken}}"
#        }'
POST http://localhost:8080/api/users/reissue-token
Content-Type: application/json

{
  "refreshToken": "{{RefreshToken}}"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}

###
# curl -X GET --location "http://localhost:8080/api/users/points"
#    -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmMTIzNEBlbWFpbC5jb20iLCJhdXRoIjoiQURNSU4iLCJleHAiOjE3MjE4OTA2NzMsImlhdCI6MTcyMTg4ODg3M30.ffG5GE-CrEBXqofaUPtCJnpEqO8QV8yKed-fUtsCWfY"
#    -H "Content-Type: application/json"
GET http://localhost:8080/api/users/points
Authorization: {{Authorization}}
Content-Type: application/json

###
# curl -X PATCH --location "http://localhost:8080/api/users/points"
#    -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhc2RmMTIzNEBlbWFpbC5jb20iLCJhdXRoIjoiQURNSU4iLCJleHAiOjE3MjE4OTA2NzMsImlhdCI6MTcyMTg4ODg3M30.ffG5GE-CrEBXqofaUPtCJnpEqO8QV8yKed-fUtsCWfY"
#    -H "Content-Type: application/json"
#    -d '{
#          "point": "10",
#          "type": "SUBTRACT"
#        }'
PATCH http://localhost:8080/api/users/points
Authorization: {{Authorization}}
Content-Type: application/json

{
  "point": "10",
  "type": "SUBTRACT"
}

###