### 로그인
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email" : "asdf1234@email.com",
  "password" : "Asdf1234!"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}

### POST 게시글 생성
POST http://localhost:8080/api/community
Content-Type: application/json
Authorization: {{Authorization}}

{
  "title": "Title14",
  "content": "contents",
  "category": "GOSSIP"
}

### PUT 게시글 수정
PUT http://localhost:8080/api/community/1
Content-Type: application/json
Authorization: {{Authorization}}

{
  "content": "update contents"
}

### GET 게시글 전체 조회
GET http://localhost:8080/api/community
Content-Type: application/json
Authorization: {{Authorization}}

### GET 게시글 단건 조회
GET http://localhost:8080/api/community/2
Content-Type: application/json
Authorization: {{Authorization}}

### DELETE 게시글 삭제
DELETE http://localhost:8080/api/community/1
Content-Type: application/json
Authorization: {{Authorization}}

### GET 게시글 검색
GET http://localhost:8080/api/community/search?keyword=ti&page=1
Content-Type: application/json
Authorization: {{Authorization}}