### 로그인
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email" : "asdf1234@email.com",
  "password" : "Asdf1234!"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}


### POST 게시글 댓글
POST http://localhost:8080/api/community/2/comments
Content-Type: application/json
Authorization: {{Authorization}}

{
  "contents" : "contents"
}

### PUT 게시글 댓글 업데이트
PUT http://localhost:8080/api/community/2/comments/1
Content-Type: application/json
Authorization: {{Authorization}}

{
  "contents" : "updates contents"
}

### GET 게시글별 댓글 조회
GET http://localhost:8080/api/community/2/comments
Content-Type: application/json
Authorization: {{Authorization}}

### DELETE 댓글 삭제
DELETE http://localhost:8080/api/community/2/comments/2
Content-Type: application/json
Authorization: {{Authorization}}