### 로그인
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email" : "asdf1234@email.com",
  "password" : "Asdf1234!"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}

### 팀 매칭 신청
POST http://localhost:8080/api/teams/match
Content-Type: application/json
Authorization: {{Authorization}}

### 팀 생성
POST http://localhost:8080/api/teams/create
Content-Type: application/json
Authorization: {{Authorization}}

### 팀 조회
GET http://localhost:8080/api/teams/2
Content-Type: application/json
Authorization: {{Authorization}}