name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.1.1'

      - name: Set executable permissions for Gradle Wrapper
        run: chmod +x ./gradlew # 실행 권한 부여

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: myrepo/myapp:latest

      - name: Upload .env file if exists
        if: ${{ secrets.ENV_FILE_PATH != '' }}
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Check if .env file exists in artifacts
            if [ -f /home/ubuntu/myapp/.env ]; then
              echo ".env file exists, proceeding to download and deploy."
              aws s3 cp s3://your-bucket/path/to/.env /home/ubuntu/myapp/.env
            else
              echo ".env file does not exist, skipping download."
            fi

            cd /home/ubuntu/myapp
            docker-compose down
            docker-compose pull
            docker-compose up -d
